version: '3'

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - docker-registry-data:/data
  registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
      - "8086:80"
    env_file: .env
    environment:
      - REGISTRY_USERNAME=${REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
      - REGISTRY_HOST=docker-registry
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=${REGISTRY_UI_USERNAME}
      - PASSWORD=${REGISTRY_UI_PASSWORD}
    restart: always
    depends_on:
      - docker-registry


volumes:
  docker-registry-data:
